// automatically generated by the FlatBuffers compiler, do not modify

package com.at.flatbuffer.model;

@SuppressWarnings("unused")
public final class Gender {
  private Gender() { }
  public static final byte Male = 0;
  public static final byte Female = 1;
  public static final byte Other = 2;

  public static final String[] names = { "Male", "Female", "Other", };

  public static String name(int e) { return names[e]; }
}

