// automatically generated by the FlatBuffers compiler, do not modify

package com.at.flatbuffer.model;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Work extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static Work getRootAsWork(ByteBuffer _bb) { return getRootAsWork(_bb, new Work()); }
  public static Work getRootAsWork(ByteBuffer _bb, Work obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Work __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long timestamp() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String company() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer companyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer companyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String position() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer positionAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer positionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String description() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer descriptionAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer descriptionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public long startDate() { int o = __offset(12); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long endDate() { int o = __offset(14); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createWork(FlatBufferBuilder builder,
      long timestamp,
      int companyOffset,
      int positionOffset,
      int descriptionOffset,
      long startDate,
      long endDate) {
    builder.startTable(6);
    Work.addEndDate(builder, endDate);
    Work.addStartDate(builder, startDate);
    Work.addTimestamp(builder, timestamp);
    Work.addDescription(builder, descriptionOffset);
    Work.addPosition(builder, positionOffset);
    Work.addCompany(builder, companyOffset);
    return Work.endWork(builder);
  }

  public static void startWork(FlatBufferBuilder builder) { builder.startTable(6); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(0, timestamp, 0L); }
  public static void addCompany(FlatBufferBuilder builder, int companyOffset) { builder.addOffset(1, companyOffset, 0); }
  public static void addPosition(FlatBufferBuilder builder, int positionOffset) { builder.addOffset(2, positionOffset, 0); }
  public static void addDescription(FlatBufferBuilder builder, int descriptionOffset) { builder.addOffset(3, descriptionOffset, 0); }
  public static void addStartDate(FlatBufferBuilder builder, long startDate) { builder.addLong(4, startDate, 0L); }
  public static void addEndDate(FlatBufferBuilder builder, long endDate) { builder.addLong(5, endDate, 0L); }
  public static int endWork(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Work get(int j) { return get(new Work(), j); }
    public Work get(Work obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

