// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.at.protobuf.model;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.at.protobuf.model.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.com.at.protobuf.model.Gender gender = 3;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.com.at.protobuf.model.Gender gender = 3;</code>
   * @return The gender.
   */
  Gender getGender();

  /**
   * <code>string address = 4;</code>
   * @return The address.
   */
  String getAddress();
  /**
   * <code>string address = 4;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int64 phone = 5;</code>
   * @return The phone.
   */
  long getPhone();

  /**
   * <code>repeated string skills = 6;</code>
   * @return A list containing the skills.
   */
  java.util.List<String>
      getSkillsList();
  /**
   * <code>repeated string skills = 6;</code>
   * @return The count of skills.
   */
  int getSkillsCount();
  /**
   * <code>repeated string skills = 6;</code>
   * @param index The index of the element to return.
   * @return The skills at the given index.
   */
  String getSkills(int index);
  /**
   * <code>repeated string skills = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the skills at the given index.
   */
  com.google.protobuf.ByteString
      getSkillsBytes(int index);

  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  java.util.List<Work>
      getWorksList();
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  Work getWorks(int index);
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  int getWorksCount();
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  java.util.List<? extends WorkOrBuilder>
      getWorksOrBuilderList();
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  WorkOrBuilder getWorksOrBuilder(
      int index);

  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */
  int getAdditionalInfoCount();
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */
  boolean containsAdditionalInfo(
      String key);
  /**
   * Use {@link #getAdditionalInfoMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Work>
  getAdditionalInfo();
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */
  java.util.Map<String, Work>
  getAdditionalInfoMap();
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */

  /* nullable */
Work getAdditionalInfoOrDefault(
      String key,
      /* nullable */
Work defaultValue);
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */

  Work getAdditionalInfoOrThrow(
      String key);
}
