// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.at.protobuf.model;

/**
 * Protobuf type {@code com.at.protobuf.model.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.at.protobuf.model.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    name_ = "";
    gender_ = 0;
    address_ = "";
    skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    works_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PersonProto.internal_static_com_at_protobuf_model_Person_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 8:
        return internalGetAdditionalInfo();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PersonProto.internal_static_com_at_protobuf_model_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Person.class, Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @Override
  public int getAge() {
    return age_;
  }

  public static final int GENDER_FIELD_NUMBER = 3;
  private int gender_;
  /**
   * <code>.com.at.protobuf.model.Gender gender = 3;</code>
   * @return The enum numeric value on the wire for gender.
   */
  @Override public int getGenderValue() {
    return gender_;
  }
  /**
   * <code>.com.at.protobuf.model.Gender gender = 3;</code>
   * @return The gender.
   */
  @Override public Gender getGender() {
    @SuppressWarnings("deprecation")
    Gender result = Gender.valueOf(gender_);
    return result == null ? Gender.UNRECOGNIZED : result;
  }

  public static final int ADDRESS_FIELD_NUMBER = 4;
  private volatile Object address_;
  /**
   * <code>string address = 4;</code>
   * @return The address.
   */
  @Override
  public String getAddress() {
    Object ref = address_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 4;</code>
   * @return The bytes for address.
   */
  @Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    Object ref = address_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_FIELD_NUMBER = 5;
  private long phone_;
  /**
   * <code>int64 phone = 5;</code>
   * @return The phone.
   */
  @Override
  public long getPhone() {
    return phone_;
  }

  public static final int SKILLS_FIELD_NUMBER = 6;
  private com.google.protobuf.LazyStringList skills_;
  /**
   * <code>repeated string skills = 6;</code>
   * @return A list containing the skills.
   */
  public com.google.protobuf.ProtocolStringList
      getSkillsList() {
    return skills_;
  }
  /**
   * <code>repeated string skills = 6;</code>
   * @return The count of skills.
   */
  public int getSkillsCount() {
    return skills_.size();
  }
  /**
   * <code>repeated string skills = 6;</code>
   * @param index The index of the element to return.
   * @return The skills at the given index.
   */
  public String getSkills(int index) {
    return skills_.get(index);
  }
  /**
   * <code>repeated string skills = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the skills at the given index.
   */
  public com.google.protobuf.ByteString
      getSkillsBytes(int index) {
    return skills_.getByteString(index);
  }

  public static final int WORKS_FIELD_NUMBER = 7;
  private java.util.List<Work> works_;
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  @Override
  public java.util.List<Work> getWorksList() {
    return works_;
  }
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  @Override
  public java.util.List<? extends WorkOrBuilder>
      getWorksOrBuilderList() {
    return works_;
  }
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  @Override
  public int getWorksCount() {
    return works_.size();
  }
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  @Override
  public Work getWorks(int index) {
    return works_.get(index);
  }
  /**
   * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
   */
  @Override
  public WorkOrBuilder getWorksOrBuilder(
      int index) {
    return works_.get(index);
  }

  public static final int ADDITIONAL_INFO_FIELD_NUMBER = 8;
  private static final class AdditionalInfoDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, Work> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, Work>newDefaultInstance(
                PersonProto.internal_static_com_at_protobuf_model_Person_AdditionalInfoEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                Work.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, Work> additionalInfo_;
  private com.google.protobuf.MapField<String, Work>
  internalGetAdditionalInfo() {
    if (additionalInfo_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AdditionalInfoDefaultEntryHolder.defaultEntry);
    }
    return additionalInfo_;
  }

  public int getAdditionalInfoCount() {
    return internalGetAdditionalInfo().getMap().size();
  }
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */

  @Override
  public boolean containsAdditionalInfo(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetAdditionalInfo().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAdditionalInfoMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, Work> getAdditionalInfo() {
    return getAdditionalInfoMap();
  }
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */
  @Override

  public java.util.Map<String, Work> getAdditionalInfoMap() {
    return internalGetAdditionalInfo().getMap();
  }
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */
  @Override

  public Work getAdditionalInfoOrDefault(
      String key,
      Work defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, Work> map =
        internalGetAdditionalInfo().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
   */
  @Override

  public Work getAdditionalInfoOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, Work> map =
        internalGetAdditionalInfo().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    if (gender_ != Gender.Male.getNumber()) {
      output.writeEnum(3, gender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
    }
    if (phone_ != 0L) {
      output.writeInt64(5, phone_);
    }
    for (int i = 0; i < skills_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, skills_.getRaw(i));
    }
    for (int i = 0; i < works_.size(); i++) {
      output.writeMessage(7, works_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAdditionalInfo(),
        AdditionalInfoDefaultEntryHolder.defaultEntry,
        8);
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    if (gender_ != Gender.Male.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, gender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
    }
    if (phone_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, phone_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < skills_.size(); i++) {
        dataSize += computeStringSizeNoTag(skills_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSkillsList().size();
    }
    for (int i = 0; i < works_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, works_.get(i));
    }
    for (java.util.Map.Entry<String, Work> entry
         : internalGetAdditionalInfo().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, Work>
      additionalInfo__ = AdditionalInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, additionalInfo__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Person)) {
      return super.equals(obj);
    }
    Person other = (Person) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (gender_ != other.gender_) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getPhone()
        != other.getPhone()) return false;
    if (!getSkillsList()
        .equals(other.getSkillsList())) return false;
    if (!getWorksList()
        .equals(other.getWorksList())) return false;
    if (!internalGetAdditionalInfo().equals(
        other.internalGetAdditionalInfo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + PHONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPhone());
    if (getSkillsCount() > 0) {
      hash = (37 * hash) + SKILLS_FIELD_NUMBER;
      hash = (53 * hash) + getSkillsList().hashCode();
    }
    if (getWorksCount() > 0) {
      hash = (37 * hash) + WORKS_FIELD_NUMBER;
      hash = (53 * hash) + getWorksList().hashCode();
    }
    if (!internalGetAdditionalInfo().getMap().isEmpty()) {
      hash = (37 * hash) + ADDITIONAL_INFO_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAdditionalInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.at.protobuf.model.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.at.protobuf.model.Person)
      PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonProto.internal_static_com_at_protobuf_model_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetAdditionalInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableAdditionalInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonProto.internal_static_com_at_protobuf_model_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    // Construct using com.at.protobuf.model.Person.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      name_ = "";

      age_ = 0;

      gender_ = 0;

      address_ = "";

      phone_ = 0L;

      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (worksBuilder_ == null) {
        works_ = java.util.Collections.emptyList();
      } else {
        works_ = null;
        worksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableAdditionalInfo().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PersonProto.internal_static_com_at_protobuf_model_Person_descriptor;
    }

    @Override
    public Person getDefaultInstanceForType() {
      return Person.getDefaultInstance();
    }

    @Override
    public Person build() {
      Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Person buildPartial() {
      Person result = new Person(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.age_ = age_;
      result.gender_ = gender_;
      result.address_ = address_;
      result.phone_ = phone_;
      if (((bitField0_ & 0x00000001) != 0)) {
        skills_ = skills_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.skills_ = skills_;
      if (worksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          works_ = java.util.Collections.unmodifiableList(works_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.works_ = works_;
      } else {
        result.works_ = worksBuilder_.build();
      }
      result.additionalInfo_ = internalGetAdditionalInfo();
      result.additionalInfo_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Person) {
        return mergeFrom((Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Person other) {
      if (other == Person.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getPhone() != 0L) {
        setPhone(other.getPhone());
      }
      if (!other.skills_.isEmpty()) {
        if (skills_.isEmpty()) {
          skills_ = other.skills_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSkillsIsMutable();
          skills_.addAll(other.skills_);
        }
        onChanged();
      }
      if (worksBuilder_ == null) {
        if (!other.works_.isEmpty()) {
          if (works_.isEmpty()) {
            works_ = other.works_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureWorksIsMutable();
            works_.addAll(other.works_);
          }
          onChanged();
        }
      } else {
        if (!other.works_.isEmpty()) {
          if (worksBuilder_.isEmpty()) {
            worksBuilder_.dispose();
            worksBuilder_ = null;
            works_ = other.works_;
            bitField0_ = (bitField0_ & ~0x00000002);
            worksBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWorksFieldBuilder() : null;
          } else {
            worksBuilder_.addAllMessages(other.works_);
          }
        }
      }
      internalGetMutableAdditionalInfo().mergeFrom(
          other.internalGetAdditionalInfo());
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              age_ = input.readInt32();

              break;
            } // case 16
            case 24: {
              gender_ = input.readEnum();

              break;
            } // case 24
            case 34: {
              address_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 40: {
              phone_ = input.readInt64();

              break;
            } // case 40
            case 50: {
              String s = input.readStringRequireUtf8();
              ensureSkillsIsMutable();
              skills_.add(s);
              break;
            } // case 50
            case 58: {
              Work m =
                  input.readMessage(
                      Work.parser(),
                      extensionRegistry);
              if (worksBuilder_ == null) {
                ensureWorksIsMutable();
                works_.add(m);
              } else {
                worksBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 66: {
              com.google.protobuf.MapEntry<String, Work>
              additionalInfo__ = input.readMessage(
                  AdditionalInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableAdditionalInfo().getMutableMap().put(
                  additionalInfo__.getKey(), additionalInfo__.getValue());
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {

      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      name_ = value;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {

      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {

      age_ = 0;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <code>.com.at.protobuf.model.Gender gender = 3;</code>
     * @return The enum numeric value on the wire for gender.
     */
    @Override public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.com.at.protobuf.model.Gender gender = 3;</code>
     * @param value The enum numeric value on the wire for gender to set.
     * @return This builder for chaining.
     */
    public Builder setGenderValue(int value) {

      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.at.protobuf.model.Gender gender = 3;</code>
     * @return The gender.
     */
    @Override
    public Gender getGender() {
      @SuppressWarnings("deprecation")
      Gender result = Gender.valueOf(gender_);
      return result == null ? Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.at.protobuf.model.Gender gender = 3;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }

      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.at.protobuf.model.Gender gender = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {

      gender_ = 0;
      onChanged();
      return this;
    }

    private Object address_ = "";
    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    public String getAddress() {
      Object ref = address_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 4;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {

      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 4;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      address_ = value;
      onChanged();
      return this;
    }

    private long phone_ ;
    /**
     * <code>int64 phone = 5;</code>
     * @return The phone.
     */
    @Override
    public long getPhone() {
      return phone_;
    }
    /**
     * <code>int64 phone = 5;</code>
     * @param value The phone to set.
     * @return This builder for chaining.
     */
    public Builder setPhone(long value) {

      phone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 phone = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone() {

      phone_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureSkillsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skills_ = new com.google.protobuf.LazyStringArrayList(skills_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @return A list containing the skills.
     */
    public com.google.protobuf.ProtocolStringList
        getSkillsList() {
      return skills_.getUnmodifiableView();
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @return The count of skills.
     */
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    public String getSkills(int index) {
      return skills_.get(index);
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the skills at the given index.
     */
    public com.google.protobuf.ByteString
        getSkillsBytes(int index) {
      return skills_.getByteString(index);
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @param index The index to set the value at.
     * @param value The skills to set.
     * @return This builder for chaining.
     */
    public Builder setSkills(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
      skills_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @param value The skills to add.
     * @return This builder for chaining.
     */
    public Builder addSkills(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureSkillsIsMutable();
      skills_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @param values The skills to add.
     * @return This builder for chaining.
     */
    public Builder addAllSkills(
        Iterable<String> values) {
      ensureSkillsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, skills_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkills() {
      skills_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string skills = 6;</code>
     * @param value The bytes of the skills to add.
     * @return This builder for chaining.
     */
    public Builder addSkillsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureSkillsIsMutable();
      skills_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Work> works_ =
      java.util.Collections.emptyList();
    private void ensureWorksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        works_ = new java.util.ArrayList<Work>(works_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Work, Work.Builder, WorkOrBuilder> worksBuilder_;

    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public java.util.List<Work> getWorksList() {
      if (worksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(works_);
      } else {
        return worksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public int getWorksCount() {
      if (worksBuilder_ == null) {
        return works_.size();
      } else {
        return worksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Work getWorks(int index) {
      if (worksBuilder_ == null) {
        return works_.get(index);
      } else {
        return worksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder setWorks(
        int index, Work value) {
      if (worksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorksIsMutable();
        works_.set(index, value);
        onChanged();
      } else {
        worksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder setWorks(
        int index, Work.Builder builderForValue) {
      if (worksBuilder_ == null) {
        ensureWorksIsMutable();
        works_.set(index, builderForValue.build());
        onChanged();
      } else {
        worksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder addWorks(Work value) {
      if (worksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorksIsMutable();
        works_.add(value);
        onChanged();
      } else {
        worksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder addWorks(
        int index, Work value) {
      if (worksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorksIsMutable();
        works_.add(index, value);
        onChanged();
      } else {
        worksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder addWorks(
        Work.Builder builderForValue) {
      if (worksBuilder_ == null) {
        ensureWorksIsMutable();
        works_.add(builderForValue.build());
        onChanged();
      } else {
        worksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder addWorks(
        int index, Work.Builder builderForValue) {
      if (worksBuilder_ == null) {
        ensureWorksIsMutable();
        works_.add(index, builderForValue.build());
        onChanged();
      } else {
        worksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder addAllWorks(
        Iterable<? extends Work> values) {
      if (worksBuilder_ == null) {
        ensureWorksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, works_);
        onChanged();
      } else {
        worksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder clearWorks() {
      if (worksBuilder_ == null) {
        works_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        worksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Builder removeWorks(int index) {
      if (worksBuilder_ == null) {
        ensureWorksIsMutable();
        works_.remove(index);
        onChanged();
      } else {
        worksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Work.Builder getWorksBuilder(
        int index) {
      return getWorksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public WorkOrBuilder getWorksOrBuilder(
        int index) {
      if (worksBuilder_ == null) {
        return works_.get(index);  } else {
        return worksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public java.util.List<? extends WorkOrBuilder>
         getWorksOrBuilderList() {
      if (worksBuilder_ != null) {
        return worksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(works_);
      }
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Work.Builder addWorksBuilder() {
      return getWorksFieldBuilder().addBuilder(
          Work.getDefaultInstance());
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public Work.Builder addWorksBuilder(
        int index) {
      return getWorksFieldBuilder().addBuilder(
          index, Work.getDefaultInstance());
    }
    /**
     * <code>repeated .com.at.protobuf.model.Work works = 7;</code>
     */
    public java.util.List<Work.Builder>
         getWorksBuilderList() {
      return getWorksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Work, Work.Builder, WorkOrBuilder>
        getWorksFieldBuilder() {
      if (worksBuilder_ == null) {
        worksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Work, Work.Builder, WorkOrBuilder>(
                works_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        works_ = null;
      }
      return worksBuilder_;
    }

    private com.google.protobuf.MapField<
        String, Work> additionalInfo_;
    private com.google.protobuf.MapField<String, Work>
    internalGetAdditionalInfo() {
      if (additionalInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AdditionalInfoDefaultEntryHolder.defaultEntry);
      }
      return additionalInfo_;
    }
    private com.google.protobuf.MapField<String, Work>
    internalGetMutableAdditionalInfo() {
      onChanged();;
      if (additionalInfo_ == null) {
        additionalInfo_ = com.google.protobuf.MapField.newMapField(
            AdditionalInfoDefaultEntryHolder.defaultEntry);
      }
      if (!additionalInfo_.isMutable()) {
        additionalInfo_ = additionalInfo_.copy();
      }
      return additionalInfo_;
    }

    public int getAdditionalInfoCount() {
      return internalGetAdditionalInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */

    @Override
    public boolean containsAdditionalInfo(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAdditionalInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAdditionalInfoMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, Work> getAdditionalInfo() {
      return getAdditionalInfoMap();
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */
    @Override

    public java.util.Map<String, Work> getAdditionalInfoMap() {
      return internalGetAdditionalInfo().getMap();
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */
    @Override

    public Work getAdditionalInfoOrDefault(
        String key,
        Work defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, Work> map =
          internalGetAdditionalInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */
    @Override

    public Work getAdditionalInfoOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, Work> map =
          internalGetAdditionalInfo().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAdditionalInfo() {
      internalGetMutableAdditionalInfo().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */

    public Builder removeAdditionalInfo(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableAdditionalInfo().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, Work>
    getMutableAdditionalInfo() {
      return internalGetMutableAdditionalInfo().getMutableMap();
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */
    public Builder putAdditionalInfo(
        String key,
        Work value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableAdditionalInfo().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .com.at.protobuf.model.Work&gt; additional_info = 8;</code>
     */

    public Builder putAllAdditionalInfo(
        java.util.Map<String, Work> values) {
      internalGetMutableAdditionalInfo().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.at.protobuf.model.Person)
  }

  // @@protoc_insertion_point(class_scope:com.at.protobuf.model.Person)
  private static final Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Person();
  }

  public static Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @Override
  public Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

