// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.at.protobuf.model;

public interface WorkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.at.protobuf.model.Work)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  String getCompany();
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>string position = 3;</code>
   * @return The position.
   */
  String getPosition();
  /**
   * <code>string position = 3;</code>
   * @return The bytes for position.
   */
  com.google.protobuf.ByteString
      getPositionBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int64 start_date = 5;</code>
   * @return The startDate.
   */
  long getStartDate();

  /**
   * <code>int64 end_date = 6;</code>
   * @return The endDate.
   */
  long getEndDate();
}
