// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.at.protobuf.model;

/**
 * Protobuf type {@code com.at.protobuf.model.Work}
 */
public final class Work extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.at.protobuf.model.Work)
    WorkOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Work.newBuilder() to construct.
  private Work(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Work() {
    company_ = "";
    position_ = "";
    description_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Work();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PersonProto.internal_static_com_at_protobuf_model_Work_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PersonProto.internal_static_com_at_protobuf_model_Work_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Work.class, Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int COMPANY_FIELD_NUMBER = 2;
  private volatile Object company_;
  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  @Override
  public String getCompany() {
    Object ref = company_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      company_ = s;
      return s;
    }
  }
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  @Override
  public com.google.protobuf.ByteString
      getCompanyBytes() {
    Object ref = company_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      company_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POSITION_FIELD_NUMBER = 3;
  private volatile Object position_;
  /**
   * <code>string position = 3;</code>
   * @return The position.
   */
  @Override
  public String getPosition() {
    Object ref = position_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      position_ = s;
      return s;
    }
  }
  /**
   * <code>string position = 3;</code>
   * @return The bytes for position.
   */
  @Override
  public com.google.protobuf.ByteString
      getPositionBytes() {
    Object ref = position_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      position_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile Object description_;
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @Override
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int START_DATE_FIELD_NUMBER = 5;
  private long startDate_;
  /**
   * <code>int64 start_date = 5;</code>
   * @return The startDate.
   */
  @Override
  public long getStartDate() {
    return startDate_;
  }

  public static final int END_DATE_FIELD_NUMBER = 6;
  private long endDate_;
  /**
   * <code>int64 end_date = 6;</code>
   * @return The endDate.
   */
  @Override
  public long getEndDate() {
    return endDate_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(position_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, position_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (startDate_ != 0L) {
      output.writeInt64(5, startDate_);
    }
    if (endDate_ != 0L) {
      output.writeInt64(6, endDate_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(company_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(position_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, position_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (startDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, startDate_);
    }
    if (endDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, endDate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Work)) {
      return super.equals(obj);
    }
    Work other = (Work) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getCompany()
        .equals(other.getCompany())) return false;
    if (!getPosition()
        .equals(other.getPosition())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getStartDate()
        != other.getStartDate()) return false;
    if (getEndDate()
        != other.getEndDate()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + COMPANY_FIELD_NUMBER;
    hash = (53 * hash) + getCompany().hashCode();
    hash = (37 * hash) + POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getPosition().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + START_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartDate());
    hash = (37 * hash) + END_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndDate());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Work parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Work parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Work parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Work parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Work parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Work parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Work parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Work parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Work parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Work parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Work parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Work parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Work prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.at.protobuf.model.Work}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.at.protobuf.model.Work)
      WorkOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonProto.internal_static_com_at_protobuf_model_Work_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonProto.internal_static_com_at_protobuf_model_Work_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Work.class, Builder.class);
    }

    // Construct using com.at.protobuf.model.Work.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      company_ = "";

      position_ = "";

      description_ = "";

      startDate_ = 0L;

      endDate_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PersonProto.internal_static_com_at_protobuf_model_Work_descriptor;
    }

    @Override
    public Work getDefaultInstanceForType() {
      return Work.getDefaultInstance();
    }

    @Override
    public Work build() {
      Work result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Work buildPartial() {
      Work result = new Work(this);
      result.timestamp_ = timestamp_;
      result.company_ = company_;
      result.position_ = position_;
      result.description_ = description_;
      result.startDate_ = startDate_;
      result.endDate_ = endDate_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Work) {
        return mergeFrom((Work)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Work other) {
      if (other == Work.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getCompany().isEmpty()) {
        company_ = other.company_;
        onChanged();
      }
      if (!other.getPosition().isEmpty()) {
        position_ = other.position_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getStartDate() != 0L) {
        setStartDate(other.getStartDate());
      }
      if (other.getEndDate() != 0L) {
        setEndDate(other.getEndDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestamp_ = input.readInt64();

              break;
            } // case 8
            case 18: {
              company_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              position_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              description_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 40: {
              startDate_ = input.readInt64();

              break;
            } // case 40
            case 48: {
              endDate_ = input.readInt64();

              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {

      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private Object company_ = "";
    /**
     * <code>string company = 2;</code>
     * @return The company.
     */
    public String getCompany() {
      Object ref = company_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        company_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string company = 2;</code>
     * @return The bytes for company.
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company = 2;</code>
     * @param value The company to set.
     * @return This builder for chaining.
     */
    public Builder setCompany(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      company_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompany() {

      company_ = getDefaultInstance().getCompany();
      onChanged();
      return this;
    }
    /**
     * <code>string company = 2;</code>
     * @param value The bytes for company to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      company_ = value;
      onChanged();
      return this;
    }

    private Object position_ = "";
    /**
     * <code>string position = 3;</code>
     * @return The position.
     */
    public String getPosition() {
      Object ref = position_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        position_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string position = 3;</code>
     * @return The bytes for position.
     */
    public com.google.protobuf.ByteString
        getPositionBytes() {
      Object ref = position_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string position = 3;</code>
     * @param value The position to set.
     * @return This builder for chaining.
     */
    public Builder setPosition(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      position_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string position = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPosition() {

      position_ = getDefaultInstance().getPosition();
      onChanged();
      return this;
    }
    /**
     * <code>string position = 3;</code>
     * @param value The bytes for position to set.
     * @return This builder for chaining.
     */
    public Builder setPositionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      position_ = value;
      onChanged();
      return this;
    }

    private Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {

      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      description_ = value;
      onChanged();
      return this;
    }

    private long startDate_ ;
    /**
     * <code>int64 start_date = 5;</code>
     * @return The startDate.
     */
    @Override
    public long getStartDate() {
      return startDate_;
    }
    /**
     * <code>int64 start_date = 5;</code>
     * @param value The startDate to set.
     * @return This builder for chaining.
     */
    public Builder setStartDate(long value) {

      startDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 start_date = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartDate() {

      startDate_ = 0L;
      onChanged();
      return this;
    }

    private long endDate_ ;
    /**
     * <code>int64 end_date = 6;</code>
     * @return The endDate.
     */
    @Override
    public long getEndDate() {
      return endDate_;
    }
    /**
     * <code>int64 end_date = 6;</code>
     * @param value The endDate to set.
     * @return This builder for chaining.
     */
    public Builder setEndDate(long value) {

      endDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 end_date = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndDate() {

      endDate_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.at.protobuf.model.Work)
  }

  // @@protoc_insertion_point(class_scope:com.at.protobuf.model.Work)
  private static final Work DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Work();
  }

  public static Work getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Work>
      PARSER = new com.google.protobuf.AbstractParser<Work>() {
    @Override
    public Work parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Work> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Work> getParserForType() {
    return PARSER;
  }

  @Override
  public Work getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

