// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserMessageInfo.proto

package com.at.pb;

public final class UserMessageInfoProto {
  private UserMessageInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserMessageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserMessageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 update_time = 1;</code>
     */
    long getUpdateTime();

    /**
     * <code>uint64 id_card = 2;</code>
     */
    long getIdCard();

    /**
     * <code>string name = 3;</code>
     */
    String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 sex = 4;</code>
     */
    int getSex();

    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */
    int getUserAddrCount();
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */
    boolean containsUserAddr(
        String key);
    /**
     * Use {@link #getUserAddrMap()} instead.
     */
    @Deprecated
    java.util.Map<String, Address>
    getUserAddr();
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */
    java.util.Map<String, Address>
    getUserAddrMap();
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */

    Address getUserAddrOrDefault(
        String key,
        Address defaultValue);
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */

    Address getUserAddrOrThrow(
        String key);
  }
  /**
   * Protobuf type {@code UserMessageInfo}
   */
  public  static final class UserMessageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserMessageInfo)
      UserMessageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserMessageInfo.newBuilder() to construct.
    private UserMessageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserMessageInfo() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserMessageInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserMessageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              updateTime_ = input.readUInt64();
              break;
            }
            case 16: {

              idCard_ = input.readUInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              sex_ = input.readUInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                userAddr_ = com.google.protobuf.MapField.newMapField(
                    UserAddrDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, Address>
              userAddr__ = input.readMessage(
                  UserAddrDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              userAddr_.getMutableMap().put(
                  userAddr__.getKey(), userAddr__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserMessageInfoProto.internal_static_UserMessageInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetUserAddr();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserMessageInfoProto.internal_static_UserMessageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserMessageInfo.class, Builder.class);
    }

    public static final int UPDATE_TIME_FIELD_NUMBER = 1;
    private long updateTime_;
    /**
     * <code>uint64 update_time = 1;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    public static final int ID_CARD_FIELD_NUMBER = 2;
    private long idCard_;
    /**
     * <code>uint64 id_card = 2;</code>
     */
    public long getIdCard() {
      return idCard_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>uint32 sex = 4;</code>
     */
    public int getSex() {
      return sex_;
    }

    public static final int USER_ADDR_FIELD_NUMBER = 5;
    private static final class UserAddrDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, Address> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, Address>newDefaultInstance(
                  UserMessageInfoProto.internal_static_UserMessageInfo_UserAddrEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  Address.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, Address> userAddr_;
    private com.google.protobuf.MapField<String, Address>
    internalGetUserAddr() {
      if (userAddr_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserAddrDefaultEntryHolder.defaultEntry);
      }
      return userAddr_;
    }

    public int getUserAddrCount() {
      return internalGetUserAddr().getMap().size();
    }
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */

    public boolean containsUserAddr(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetUserAddr().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserAddrMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Address> getUserAddr() {
      return getUserAddrMap();
    }
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */

    public java.util.Map<String, Address> getUserAddrMap() {
      return internalGetUserAddr().getMap();
    }
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */

    public Address getUserAddrOrDefault(
        String key,
        Address defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Address> map =
          internalGetUserAddr().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
     */

    public Address getUserAddrOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Address> map =
          internalGetUserAddr().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (updateTime_ != 0L) {
        output.writeUInt64(1, updateTime_);
      }
      if (idCard_ != 0L) {
        output.writeUInt64(2, idCard_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (sex_ != 0) {
        output.writeUInt32(4, sex_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetUserAddr(),
          UserAddrDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, updateTime_);
      }
      if (idCard_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, idCard_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, sex_);
      }
      for (java.util.Map.Entry<String, Address> entry
           : internalGetUserAddr().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, Address>
        userAddr__ = UserAddrDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, userAddr__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserMessageInfo)) {
        return super.equals(obj);
      }
      UserMessageInfo other = (UserMessageInfo) obj;

      if (getUpdateTime()
          != other.getUpdateTime()) return false;
      if (getIdCard()
          != other.getIdCard()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getSex()
          != other.getSex()) return false;
      if (!internalGetUserAddr().equals(
          other.internalGetUserAddr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (37 * hash) + ID_CARD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIdCard());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      if (!internalGetUserAddr().getMap().isEmpty()) {
        hash = (37 * hash) + USER_ADDR_FIELD_NUMBER;
        hash = (53 * hash) + internalGetUserAddr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserMessageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMessageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMessageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMessageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMessageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserMessageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserMessageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMessageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMessageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserMessageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserMessageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserMessageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserMessageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserMessageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserMessageInfo)
        UserMessageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserMessageInfoProto.internal_static_UserMessageInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetUserAddr();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableUserAddr();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserMessageInfoProto.internal_static_UserMessageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserMessageInfo.class, Builder.class);
      }

      // Construct using com.at.pb.UserMessageInfoProto.UserMessageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        updateTime_ = 0L;

        idCard_ = 0L;

        name_ = "";

        sex_ = 0;

        internalGetMutableUserAddr().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserMessageInfoProto.internal_static_UserMessageInfo_descriptor;
      }

      @Override
      public UserMessageInfo getDefaultInstanceForType() {
        return UserMessageInfo.getDefaultInstance();
      }

      @Override
      public UserMessageInfo build() {
        UserMessageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserMessageInfo buildPartial() {
        UserMessageInfo result = new UserMessageInfo(this);
        int from_bitField0_ = bitField0_;
        result.updateTime_ = updateTime_;
        result.idCard_ = idCard_;
        result.name_ = name_;
        result.sex_ = sex_;
        result.userAddr_ = internalGetUserAddr();
        result.userAddr_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserMessageInfo) {
          return mergeFrom((UserMessageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserMessageInfo other) {
        if (other == UserMessageInfo.getDefaultInstance()) return this;
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        if (other.getIdCard() != 0L) {
          setIdCard(other.getIdCard());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        internalGetMutableUserAddr().mergeFrom(
            other.internalGetUserAddr());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserMessageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserMessageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long updateTime_ ;
      /**
       * <code>uint64 update_time = 1;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <code>uint64 update_time = 1;</code>
       */
      public Builder setUpdateTime(long value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 update_time = 1;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0L;
        onChanged();
        return this;
      }

      private long idCard_ ;
      /**
       * <code>uint64 id_card = 2;</code>
       */
      public long getIdCard() {
        return idCard_;
      }
      /**
       * <code>uint64 id_card = 2;</code>
       */
      public Builder setIdCard(long value) {
        
        idCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 id_card = 2;</code>
       */
      public Builder clearIdCard() {
        
        idCard_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>uint32 sex = 4;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>uint32 sex = 4;</code>
       */
      public Builder setSex(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, Address> userAddr_;
      private com.google.protobuf.MapField<String, Address>
      internalGetUserAddr() {
        if (userAddr_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              UserAddrDefaultEntryHolder.defaultEntry);
        }
        return userAddr_;
      }
      private com.google.protobuf.MapField<String, Address>
      internalGetMutableUserAddr() {
        onChanged();;
        if (userAddr_ == null) {
          userAddr_ = com.google.protobuf.MapField.newMapField(
              UserAddrDefaultEntryHolder.defaultEntry);
        }
        if (!userAddr_.isMutable()) {
          userAddr_ = userAddr_.copy();
        }
        return userAddr_;
      }

      public int getUserAddrCount() {
        return internalGetUserAddr().getMap().size();
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */

      public boolean containsUserAddr(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetUserAddr().getMap().containsKey(key);
      }
      /**
       * Use {@link #getUserAddrMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Address> getUserAddr() {
        return getUserAddrMap();
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */

      public java.util.Map<String, Address> getUserAddrMap() {
        return internalGetUserAddr().getMap();
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */

      public Address getUserAddrOrDefault(
          String key,
          Address defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Address> map =
            internalGetUserAddr().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */

      public Address getUserAddrOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Address> map =
            internalGetUserAddr().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearUserAddr() {
        internalGetMutableUserAddr().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */

      public Builder removeUserAddr(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableUserAddr().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, Address>
      getMutableUserAddr() {
        return internalGetMutableUserAddr().getMutableMap();
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */
      public Builder putUserAddr(
          String key,
          Address value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableUserAddr().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .Address&gt; user_addr = 5;</code>
       */

      public Builder putAllUserAddr(
          java.util.Map<String, Address> values) {
        internalGetMutableUserAddr().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserMessageInfo)
    }

    // @@protoc_insertion_point(class_scope:UserMessageInfo)
    private static final UserMessageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserMessageInfo();
    }

    public static UserMessageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserMessageInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserMessageInfo>() {
      @Override
      public UserMessageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserMessageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserMessageInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserMessageInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public UserMessageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string city = 1;</code>
     */
    String getCity();
    /**
     * <code>string city = 1;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string addr = 2;</code>
     */
    String getAddr();
    /**
     * <code>string addr = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddrBytes();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      city_ = "";
      addr_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              addr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserMessageInfoProto.internal_static_Address_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserMessageInfoProto.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Address.class, Builder.class);
    }

    public static final int CITY_FIELD_NUMBER = 1;
    private volatile Object city_;
    /**
     * <code>string city = 1;</code>
     */
    public String getCity() {
      Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDR_FIELD_NUMBER = 2;
    private volatile Object addr_;
    /**
     * <code>string addr = 2;</code>
     */
    public String getAddr() {
      Object ref = addr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        addr_ = s;
        return s;
      }
    }
    /**
     * <code>string addr = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddrBytes() {
      Object ref = addr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        addr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, city_);
      }
      if (!getAddrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addr_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, city_);
      }
      if (!getAddrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Address)) {
        return super.equals(obj);
      }
      Address other = (Address) obj;

      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getAddr()
          .equals(other.getAddr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getAddr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserMessageInfoProto.internal_static_Address_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserMessageInfoProto.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Address.class, Builder.class);
      }

      // Construct using com.at.pb.UserMessageInfoProto.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        city_ = "";

        addr_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserMessageInfoProto.internal_static_Address_descriptor;
      }

      @Override
      public Address getDefaultInstanceForType() {
        return Address.getDefaultInstance();
      }

      @Override
      public Address build() {
        Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Address buildPartial() {
        Address result = new Address(this);
        result.city_ = city_;
        result.addr_ = addr_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Address) {
          return mergeFrom((Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Address other) {
        if (other == Address.getDefaultInstance()) return this;
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getAddr().isEmpty()) {
          addr_ = other.addr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object city_ = "";
      /**
       * <code>string city = 1;</code>
       */
      public String getCity() {
        Object ref = city_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string city = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 1;</code>
       */
      public Builder setCity(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 1;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 1;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private Object addr_ = "";
      /**
       * <code>string addr = 2;</code>
       */
      public String getAddr() {
        Object ref = addr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          addr_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string addr = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddrBytes() {
        Object ref = addr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          addr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string addr = 2;</code>
       */
      public Builder setAddr(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        addr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 2;</code>
       */
      public Builder clearAddr() {
        
        addr_ = getDefaultInstance().getAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string addr = 2;</code>
       */
      public Builder setAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        addr_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Address();
    }

    public static Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @Override
    public Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserMessageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserMessageInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserMessageInfo_UserAddrEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserMessageInfo_UserAddrEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025UserMessageInfo.proto\"\300\001\n\017UserMessageI" +
      "nfo\022\023\n\013update_time\030\001 \001(\004\022\017\n\007id_card\030\002 \001(" +
      "\004\022\014\n\004name\030\003 \001(\t\022\013\n\003sex\030\004 \001(\r\0221\n\tuser_add" +
      "r\030\005 \003(\0132\036.UserMessageInfo.UserAddrEntry\032" +
      "9\n\rUserAddrEntry\022\013\n\003key\030\001 \001(\t\022\027\n\005value\030\002" +
      " \001(\0132\010.Address:\0028\001\"%\n\007Address\022\014\n\004city\030\001 " +
      "\001(\t\022\014\n\004addr\030\002 \001(\tB%\n\tcom.at.pbB\024UserMess" +
      "ageInfoProtoH\001P\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserMessageInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserMessageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserMessageInfo_descriptor,
        new String[] { "UpdateTime", "IdCard", "Name", "Sex", "UserAddr", });
    internal_static_UserMessageInfo_UserAddrEntry_descriptor =
      internal_static_UserMessageInfo_descriptor.getNestedTypes().get(0);
    internal_static_UserMessageInfo_UserAddrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserMessageInfo_UserAddrEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new String[] { "City", "Addr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
