// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.at.protobuf.model;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_at_protobuf_model_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_at_protobuf_model_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_at_protobuf_model_Person_AdditionalInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_at_protobuf_model_Person_AdditionalInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_at_protobuf_model_Work_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_at_protobuf_model_Work_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\025com.at.protobuf.model\"\316\002" +
      "\n\006Person\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022-\n\006g" +
      "ender\030\003 \001(\0162\035.com.at.protobuf.model.Gend" +
      "er\022\017\n\007address\030\004 \001(\t\022\r\n\005phone\030\005 \001(\003\022\016\n\006sk" +
      "ills\030\006 \003(\t\022*\n\005works\030\007 \003(\0132\033.com.at.proto" +
      "buf.model.Work\022J\n\017additional_info\030\010 \003(\0132" +
      "1.com.at.protobuf.model.Person.Additiona" +
      "lInfoEntry\032R\n\023AdditionalInfoEntry\022\013\n\003key" +
      "\030\001 \001(\t\022*\n\005value\030\002 \001(\0132\033.com.at.protobuf." +
      "model.Work:\0028\001\"w\n\004Work\022\021\n\ttimestamp\030\001 \001(" +
      "\003\022\017\n\007company\030\002 \001(\t\022\020\n\010position\030\003 \001(\t\022\023\n\013" +
      "description\030\004 \001(\t\022\022\n\nstart_date\030\005 \001(\003\022\020\n" +
      "\010end_date\030\006 \001(\003*)\n\006Gender\022\010\n\004Male\020\000\022\n\n\006F" +
      "emale\020\001\022\t\n\005Other\020\002B(\n\025com.at.protobuf.mo" +
      "delB\013PersonProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_at_protobuf_model_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_at_protobuf_model_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_at_protobuf_model_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Gender", "Address", "Phone", "Skills", "Works", "AdditionalInfo", });
    internal_static_com_at_protobuf_model_Person_AdditionalInfoEntry_descriptor =
      internal_static_com_at_protobuf_model_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_at_protobuf_model_Person_AdditionalInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_at_protobuf_model_Person_AdditionalInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_at_protobuf_model_Work_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_at_protobuf_model_Work_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_at_protobuf_model_Work_descriptor,
        new java.lang.String[] { "Timestamp", "Company", "Position", "Description", "StartDate", "EndDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
